#!/bin/bash
# indexes (I think the one use per file is redunant?) then aligns reads to ref 
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm22504_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm22504_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm22504-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm22524_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm22524_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm22524-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm22544_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm22544_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm22544-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm22553_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm22553_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm22553-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm22563_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm22563_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm22563-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm24358_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm24358_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm24358-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm24374_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm24374_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm24374-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm24375_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm24375_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm24375-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_badiceps_kunhm24389_READ1.fastq.gz 2_reads/cettia_ruficapilla_badiceps_kunhm24389_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_badiceps_kunhm24389-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm24243_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm24243_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm24243-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm24270_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm24270_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm24270-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm24289_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm24289_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm24289-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm26502_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm26502_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm26502-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm26521_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm26521_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm26521-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm26535_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm26535_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm26535-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_castaneoptera_kunhm26539_READ1.fastq.gz 2_reads/cettia_ruficapilla_castaneoptera_kunhm26539_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_castaneoptera_kunhm26539-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_funebris_kunhm24305_READ1.fastq.gz 2_reads/cettia_ruficapilla_funebris_kunhm24305_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_funebris_kunhm24305-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_funebris_kunhm24325_READ1.fastq.gz 2_reads/cettia_ruficapilla_funebris_kunhm24325_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_funebris_kunhm24325-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_ruficapilla_kunhm24393_READ1.fastq.gz 2_reads/cettia_ruficapilla_ruficapilla_kunhm24393_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_ruficapilla_kunhm24393-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_ruficapilla_kunhm24399_READ1.fastq.gz 2_reads/cettia_ruficapilla_ruficapilla_kunhm24399_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_ruficapilla_kunhm24399-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_ruficapilla_kunhm24404_READ1.fastq.gz 2_reads/cettia_ruficapilla_ruficapilla_kunhm24404_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_ruficapilla_kunhm24404-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_ruficapilla_kunhm25208_READ1.fastq.gz 2_reads/cettia_ruficapilla_ruficapilla_kunhm25208_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_ruficapilla_kunhm25208-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_ruficapilla_ruficapilla_kunhm25228_READ1.fastq.gz 2_reads/cettia_ruficapilla_ruficapilla_kunhm25228_READ2.fastq.gz > 5_mapping/cettia_ruficapilla_ruficapilla_kunhm25228-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_parens_amnhdot15009-READ1.fastq.gz 2_reads/cettia_parens_amnhdot15009-READ2.fastq.gz > 5_mapping/cettia_parens_amnhdot15009-aln.sam
bwa index -a is 4_match/horo_trimmed.fasta && bwa mem 4_match/horo_trimmed.fasta 2_reads/cettia_parens_kunhm13537-READ1.fastq.gz 2_reads/cettia_parens_kunhm13537-READ2.fastq.gz > 5_mapping/cettia_parens_kunhm13537-aln.sam

